### PR TITLE
Add COSMIC category to appstream metainfo

### PR DESCRIPTION
**Pull request by jackpot51**
This will allow it to show up in a COSMIC-specific page in the COSMIC store. https://github.com/pop-os/cosmic-store/issues/167

### CODE REVIEW

**Comment by mariinkys** [comment]
Perfect, thank you!

**Comment by bbhtt** [comment]
Appstream hasn't updated its category list, so having this now will make it fail validation. 

Also it filters all DE names as low quality categories. When the category list in appstream is updated, you have to ask the appstream maintainer to not filter it if you want it in the appstream catalogue data.

See https://github.com/ximion/appstream/blob/3203d61a6bdd248ae4045e13f00cf0951786151c/src/as-utils.c#L1337

**Comment by jackpot51** [comment]
I don't see that mattering for the use case since cosmic-store does its own appstream parsing.

**Comment by bbhtt** [comment]
Are you parsing the metainfo files directly or the composed catalogue data?

If it's the latter, and the COSMIC category is filtered by appstream even if you have it in metainfo it will not be present in the catalogue data.

**Comment by jackpot51** [comment]
Parsing the composed metainfo. I will request it is not filtered out.

https://github.com/ximion/appstream/pull/669

**Comment by jackpot51** [comment]
@mariinkys I will consult more with @ximion, but for now I'd recommend to remove the COSMIC category and set project_group to COSMIC instead.

**Comment by jackpot51** [comment]
We are comsidering the following, verbatim, for identifying apps made for COSMIC:

For an app:

```
<provides>
    <id>com.system76.CosmicApplication</id>
</provides>
```

For an applet:

```
<provides>
    <id>com.system76.CosmicApplet</id>
</provides>
```

**Comment by bbhtt** [comment]
provides is also used for "merging" same applications but different ID by gnome software, discover etc. Eg. when an application goes through an ID change it adds the old ID to the provides tag, so that software store page merges the two entries instead of showing them separately.

Having `com.system76.CosmicApplication` is fine as long as you don't have another app with that ID. It's hard to ensure that though as 3rd party developers can pick random IDs and often distributions don't have policies for ID/domain verification.

The suitable tag for this doesn't exist in appstream, but maybe keyword is the best ? It allows arbitrary values and is not filtered.

Note, that you can't use the `custom` tag as that is also filtered from catalogue by appstream by default.

**Comment by jackpot51** [comment]
`com.system76.CosmicApplication` is virtual, we at System76 won't create a component with this ID, and if it was it would not be valid and we would ask for its removal. Keywords are not as tightly defined and are used for search, I think the real solution will involve a new key but for now I am okay with the potential drawbacks of provides->id.

**Comment by jackpot51** [comment]
I prefer provides->id because it santically feels closer to what we are defining, a program that provides a COSMIC toolkit based application, similar to how provides has keys for dbus and mine types. I understand this is an overloading of the real definition, but I would not want to interfere with the searchable namespace defined by keywords.

**Pull request merged**
